### ISSUE TITLE
Exiled users can still comment in the guild (Not 100% sure how they did it)

### ISSUE THREAD

**Issue by dginovker** [ruqqus/ruqqus#717] opened 2021-04-16 16:45 UTC
## Expected Behavior
Exiled users can't participate

## Current Behavior
Exiled user somehow participated

## Steps to Reproduce
These are not steps to reproduce, but steps that evidence it

1. See TheKalergiFan's comment here: https://ruqqus.com/+TheGoodDumpling/post/6jvj/lets-take-a-moment-to-see/n1ct
2. See that they were exiled 3 months ago here: https://ruqqus.com/+TheGoodDumpling/mod/log/7dg
3. See they were never unexiled in the (short) modlog: https://ruqqus.com/+TheGoodDumpling/mod/log

**Comment by IThinkImOKAY** [comment] 2021-04-16 19:05
We need timestamps for mod logs.

**Comment by dginovker** [comment] 2021-04-22 23:15
The user has continued to make posts. I can't exile them, if I try to, it tells me that they've already been exiled.

https://ruqqus.com/+general/post/9zkw/the-gm-of-this-faggy-guild

**Comment by IThinkImOKAY** [comment] 2021-04-22 23:17
Would you mind adding me as a GM?

**Comment by dginovker** [comment] 2021-04-23 01:25
Done

**Comment by IThinkImOKAY** [comment] 2021-04-23 01:34
Very weird. Not able to reproduce. Must be nice being to go around exiles...

**Comment by vulpinefoxxo** [comment] 2021-04-27 06:31
can you exile me (@foxman) to try see the problem?

**Comment by dginovker** [comment] 2021-05-04 01:19
@vulpinefoxxo Can't exile you unless you've participated in the guild. Feel free to make a post in +TheGoodDumpling and I'll axe you.

Back to the OC, Aevaan is [exiled](https://i.imgur.com/0KOzpTT.png) from +Bitcoin but still [posting](https://i.imgur.com/A5uGwcc.png) threads as well. Do exiles even work?

**Comment by IThinkImOKAY** [comment] 2021-05-04 12:07
@dginovker hover over the "1 month ago" text and you will see that that was posted after Aevann was exiled.

**Comment by captainmeta4** [comment] 2021-07-03 19:45
should be fixed now

**Closed by captainmeta4** 2021-07-03 19:45 UTC
