### ISSUE TITLE
Cloudflare returns 525 upon attempting to access the ruqqus site

### ISSUE THREAD

**Issue by DGKSK8LIFE** [ruqqus/ruqqus#458] opened 2020-09-04 20:23 UTC
Issue tracker is **ONLY** used for reporting bugs.

I try to access `https://ruqqus.com` and I get this: 
![image](https://user-images.githubusercontent.com/45473363/92282029-73145580-eec2-11ea-8663-d12f39ed1816.png)

## Expected Behavior

Should load the browse feed 

## Current Behavior

Cloudflare serves an HTTP 525 error

## Possible Solution

Heroku is down; heroku servers need better uptime assurance.

## Steps to Reproduce

1. Access `https://ruqqus.com/

**Comment by CrystalVulpine** [comment] 2020-09-04 23:04
Heroku isn't down, they banned ruqqus.

**Comment by DGKSK8LIFE** [comment] 2020-09-04 23:05
so there's confirmation now? @CrystalVulpine

**Comment by CrystalVulpine** [comment] 2020-09-04 23:07
@captainmeta4 confirmed that Heroku suspended his account. He's going to move to AWS unless Heroku unbans us.

**Comment by DGKSK8LIFE** [comment] 2020-09-04 23:08
digital ocean/GCP would be a lot cheaper @CrystalVulpine

**Comment by DGKSK8LIFE** [comment] 2020-09-04 23:09
@CrystalVulpine when will ruqqus be redeployed

**Comment by CrystalVulpine** [comment] 2020-09-04 23:09
TBD

**Comment by DGKSK8LIFE** [comment] 2020-09-04 23:10
ok so I can't depend on ruqqus' uptime this weekend? @CrystalVulpine

**Comment by CrystalVulpine** [comment] 2020-09-04 23:22
I don't know. Cap said he's switching to AWS right now, don't know how long that'll take.

**Comment by DGKSK8LIFE** [comment] 2020-09-04 23:23
k watching announcement closely @CrystalVulpine

**Comment by DarkMavrik** [comment] 2020-09-05 03:29
pretty sure I have seen numerous posts for weeks following up to this, that it was going to happen. Any particular reason for no backup plan? Or just a cost benefit thing?

**Comment by DGKSK8LIFE** [comment] 2020-09-05 03:34
Can you link the posts please @DarkMavrik. Well I think all of this was unexpected. I think we need to improve our devops infrastructure in general. Cap is taking a long ass time to do db migrations in PGSQL which should be automated anyways.

**Comment by DarkMavrik** [comment] 2020-09-05 03:43
They were on Ruqqus, in the Ruqqus guild, I had seen several of people asking to migrate away from Heroku for this exact reason. I don't have one saved or I would, it had caught my attention, but I am not a web side person.

**Comment by DGKSK8LIFE** [comment] 2020-09-05 03:51
k

**Comment by DarkMavrik** [comment] 2020-09-05 06:15
Ok so heres some links my associate found to assist in this, f[irst shot with a detailed plan to even improve and lower costs](https://webcache.googleusercontent.com/search?q=cache:qPL3SqTAj3UJ:https://ruqqus.com/post/1m61/contingency-plan-in-case-ruqqus-gets+&cd=1&hl=en&ct=clnk&gl=us) then heres a paige [where kek answered no big deal, they dont have a track record of censoring people, and making a move to aws be painless](https://webcache.googleusercontent.com/search?q=cache:um49RcfLuVoJ:https://ruqqus.com/post/e0p/the-grip-is-tightening-prepare-for+&cd=5&hl=en&ct=clnk&gl=us)

**Comment by DarkMavrik** [comment] 2020-09-05 06:17
> Ok so heres some links my associate found to assist in this, f[irst shot with a detailed plan to even improve and lower costs](https://webcache.googleusercontent.com/search?q=cache:qPL3SqTAj3UJ:https://ruqqus.com/post/1m61/contingency-plan-in-case-ruqqus-gets+&cd=1&hl=en&ct=clnk&gl=us) then heres a paige [where kek answered no big deal, they dont have a track record of censoring people, and making a move to aws be painless](https://webcache.googleusercontent.com/search?q=cache:um49RcfLuVoJ:https://ruqqus.com/post/e0p/the-grip-is-tightening-prepare-for+&cd=5&hl=en&ct=clnk&gl=us)

The comment exactly 
_

Heroku doesn't have a record of censoring. Worst case we got to AWS. We do use CloudFlare which might give us the boot in the future. I think we're good for now.

We're not using Stripe for anything. PayPal donations are a thing but I don't think Ruqqus is viewed as /pol/-tier for them to shut us out.
_

**Comment by CrystalVulpine** [comment] 2020-09-05 10:56
Ruqqus is still down :/

**Comment by DGKSK8LIFE** [comment] 2020-09-05 14:27
Yeah Cap is working on bringing it back up. May take a few hours cause of migrations and other stuff @CrystalVulpine. @DarkMavrik I think our best bet, would either be hosting bare metal, or using a bare metal VM provider like digital ocean. We could sit nginx in front of our digital ocean VMs but still use AWS services (like its cloud DB service and s3)

**Comment by DarkMavrik** [comment] 2020-09-05 15:06
your going to hit the same issues down the road again, since AWS doesn't like free speech either.

**Comment by CrystalVulpine** [comment] 2020-09-05 15:26
I don't think many companies like free speech anymore. The Democrats throw way too much money at them to make them do what they want.

This is the danger of relying on a different company for your operations. If Ruqqus cannot run its own servers, unfortunately it's probably done for. Cap is extremely lucky that he was even able to retrieve our data while his Heroku account is banned.

**Comment by DarkMavrik** [comment] 2020-09-05 15:29
@CrystalVulpine  as was mentioned in that archived post, there are options out there, some opensource.

**Comment by DGKSK8LIFE** [comment] 2020-09-05 16:13
@CrystalVulpine I suggested P2P as a viable alternative but we'd need a fuckton of instances/nodes to get a fraction of the performance we have now. I think renting out our own servers across the world could work, but it's wayy more costly than just hosting via cloud service providers. Take a look at [this service; it's a vps hosting provider and tell me what you think](https://www.vultr.com/). Those open source options require you to have networking and hardware. Hosting an app for 40k users and counting from your own home is going to be super costly; electricity and wifi be insanely expensive. I think if we just found a less corporate/liberal cloud service then we'd set. @captainmeta4 we could use [this](https://github.com/minio/minio) as a viable alternative to s3 but configuration would be a pain in the arse.

**Comment by shillshocked** [comment] 2020-09-05 22:28
Check out lowendtalk for some decent deals, also a Russian provider I like, Selectel. Russian providers tend to be anti-censorship, so long as it's not Anti-Russian.

**Comment by captainmeta4** [comment] 2020-09-07 04:33
Issue resolved by moving to aws

**Comment by DGKSK8LIFE** [comment] 2020-09-07 12:49
@captainmeta4 this error was happening when we were deployed to AWS yesterday.

**Closed** 2020-09-07 12:49 UTC
Labels: bug, infrastructure
